# Generated by Django 5.1.6 on 2025-05-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
